name: test

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
  schedule:
    - cron: "0 4 * * MON"

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest"]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    defaults:
      run:
        shell: bash -l {0}

    name: |
      os=${{ matrix.os }}
      - python=${{ matrix.python-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup conda
        uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: env.yml
          environment-name: graphormer
          cache-downloads: true
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install library
        run: python -m pip install --no-deps .

      - name: Run pytest
        run: pytest
